Make apply script with cuda

diff --git a/scripts/cucorr-tmpl.sh.in b/scripts/cucorr-tmpl.sh.in
--- a/scripts/cucorr-tmpl.sh.in
+++ b/scripts/cucorr-tmpl.sh.in
@@ -3,10 +3,49 @@
 # cucorr library
 #
 
+function parse_cuda_cmd_line() {
+  typeart_non_cuda_args=""
+  found_cuda=0
+  cuda_code_arch="sm_50"
+  cuda_compute_arch="compute_50"
+  show_cuda_ir=0
+
+  while (("$#")); do
+    case "$1" in
+    -x)
+      if [ "$2" == "cuda" ]; then
+        found_cuda=1
+      else
+        typeart_non_cuda_args="$typeart_non_cuda_args $1 $2"
+      fi
+      shift 2
+      ;;
+    --cuda-gpu-arch=*)
+      cuda_code_arch="${1##--cuda-gpu-arch=}"
+      cuda_compute_arch="compute${cuda_code_arch##sm}"
+      shift 1
+      ;;
+    --show_cuda_ir)
+      show_cuda_ir=1
+      shift 1
+      ;;
+    *) # preserve other arguments
+      typeart_non_cuda_args="$typeart_non_cuda_args $1"
+      shift
+      ;;
+    esac
+  done
+  # set other positional arguments in their proper place
+  set -- "typeart_non_cuda_args"
+}
+
 function cucorr_parse_cmd_line() {
   readonly source_file=$1
   optimize=""
   with_omp=0
+  compile_flags=""
+  show_cuda_ir=0
+  show_cuda_host_ir=0
 
   shift # skip over $1
   while (("$#")); do
@@ -42,12 +81,33 @@ function cucorr_parse_cmd_line() {
       with_omp=1
       shift
       ;;
+    --compile_flags)
+      if [ -n "$2" ]; then
+        compile_flags="$2"
+        shift 2
+      else
+        echo "Error: argument for $1 is missing." >&2
+        shift
+      fi
+    ;;
+    --show_ir)
+      show_cuda_ir=1
+      shift
+    ;;
+    --show_host_ir)
+      show_cuda_host_ir=1
+      shift
+    ;;
     *) # preserve other arguments
       more_args="$more_args $1"
       shift
       ;;
     esac
   done
+
+  if [ -z "${compile_flags}" ]; then
+    compile_flags=""
+  fi
 
   if [ -z "${object_file}" ]; then
     # use filename(source_file).o
@@ -65,17 +125,44 @@ function cucorr_parse_cmd_line() {
 }
 
 function cucorr_global_init() {
-  readonly opt_tool=@CUCORR_OPT_EXEC@
-  readonly llc_tool=@CUCORR_LLC_EXEC@
+  typeart_global_init
 
-  local -r cucorr_pass="$<TARGET_FILE:cucorr::TransformPass>"
-  local -r cucorr_lib_dir="$<TARGET_FILE_DIR:cucorr::Runtime>"
+  local -r cucorr_bin_dir="@CUCORR_BINARY_DIR@"
+  local -r cucorr_lib_dir="@CUCORR_RT_DIR@"
+  local -r cucorr_include_dir="@CUCORR_INCLUDE_DIRS@"
+  local -r cucorr_pass="@CUCORR_PASS_DIR@/$<TARGET_FILE_NAME:cucorr::TransformPass>"
+
   readonly cucorr_ldflags="-L${cucorr_lib_dir}/ \
                    -Wl,-rpath,${cucorr_lib_dir}/ \
                    -l$<TARGET_FILE_BASE_NAME:cucorr::Runtime>"
 
-  readonly cucorr_includes="@CUCORR_INCLUDE_DIRS@"
+  readonly cucorr_includes="${cucorr_include_dir}"
   readonly cucorr_plugin="-load "${cucorr_pass}" -cucorr"
+  readonly cucorr_cpu_mode=""
+  readonly cucorr_gpu_mode=""
+}
+
+function typeart_global_init() {
+  local -r typeart_bin_dir="@TYPEART_BINARY_DIR@"
+  local -r typeart_lib_dir="@TYPEART_RT_DIR@"
+  local -r typeart_include_dir="@TYPEART_INCLUDE_DIRS@"
+  local -r typeart_pass="@TYPEART_PASS_DIR@/$<TARGET_FILE_NAME:typeart::TransformPass>"
+  readonly typeart_interceptor="@TYPEART_MPI_INTERCEPT_DIR@/@TYPEART_MPI_TOOL@"
+
+
+  readonly opt_tool="@TYPEART_OPT@"
+  readonly llc_tool="@TYPEART_LLC@"
+
+  readonly typeart_includes="${typeart_include_dir}"
+  readonly typeart_ldflags="-L${typeart_lib_dir}/ \
+                   -Wl,-rpath,${typeart_lib_dir}/ \
+                   -l$<TARGET_FILE_BASE_NAME:typeart::Runtime>"
+
+  # shellcheck disable=SC2027
+  readonly typeart_plugin="-load "${typeart_pass}" -typeart"
+  readonly typeart_stack_mode_args="-typeart-heap=false -typeart-stack -typeart-stats"
+  readonly typeart_heap_mode_args="-typeart-heap=true -typeart-stats"
+  readonly typeart_combined_mode_args="${typeart_heap_mode_args} -typeart-stack"
 }
 
 function cucorr_toolchain_init() {
@@ -100,27 +187,49 @@ function cucorr_toolchain_init() {
 }
 
 function cucorr_source_to_llvm() {
-  $compiler ${omp_flags} ${cucorr_includes} ${cucorr_san_flags} \
-    -O1 ${compile_flags} -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o -
+  local cuda_add_flag=""
+  if [ $found_cuda == 1 ]; then
+    cuda_add_flag="--cuda-host-only"
+    if [ $show_cuda_ir == 1 ]; then
+      cuda_add_flag="--cuda-device-only --cuda-gpu-arch=${cuda_code_arch}"
+    elif [ $show_cuda_host_ir == 1 ]; then
+      cuda_add_flag="--cuda-host-only"
+    fi
+    cuda_add_flag+=" -x cuda"
+  fi
+  $compiler ${cuda_add_flag} ${omp_flags} ${typeart_includes} ${cucorr_include_dir} ${cucorr_san_flags} \
+    -O1 -g ${compile_flags} -Xclang -disable-llvm-passes -S -emit-llvm "${source_file}" -o -
 }
 
 function cucorr_apply_pass() {
   cucorr_source_to_llvm |
-    $opt_tool ${cucorr_plugin} ${more_args}
+    $opt_tool ${typeart_plugin} ${typeart_combined_mode_args} ${ta_more_args} -S |
+    $opt_tool ${cucorr_plugin} ${more_args} -S
 }
 
 function cucorr_apply_pass_optim() {
   cucorr_source_to_llvm |
+    $opt_tool ${typeart_plugin} ${typeart_heap_mode_args} ${ta_more_args} |
     $opt_tool ${optimize} -S |
-    $opt_tool ${cucorr_plugin} ${more_args}
+    $opt_tool ${cucorr_plugin} ${more_args} |
+    $opt_tool ${typeart_plugin} ${typeart_stack_mode_args} ${ta_more_args} -S
+
 }
 
 function cucorr_compile() {
   local llc_flags="--filetype=obj"
   if [ "$optimize" == " " ]; then
-    cucorr_apply_pass | $llc_tool -x=ir ${llc_flags} -o "${object_file}"
+    if [ $show_cuda_ir == 0 ] && [ $show_cuda_host_ir == 0 ]; then
+      cucorr_apply_pass | $llc_tool -x=ir ${llc_flags} -o "${object_file}"
+    else
+      cucorr_apply_pass
+    fi
   else
-    cucorr_apply_pass_optim | $llc_tool -x=ir ${llc_flags} -o "${object_file}"
+    if [ $show_cuda_ir == 0 ] && [ $show_cuda_host_ir == 0 ]; then
+      cucorr_apply_pass_optim | $llc_tool -x=ir ${llc_flags} -o "${object_file}"
+    else
+      cucorr_apply_pass_optim
+    fi
   fi
 }
 
@@ -134,8 +243,13 @@ function cucorr_execute() {
   LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${cucorr_lib_dir}" "${exe_file}"
 }
 
+function parse_commands() {
+  parse_cuda_cmd_line "$@"
+  cucorr_parse_cmd_line ${typeart_non_cuda_args}
+}
+
 function cucorr_main_in() {
-  cucorr_parse_cmd_line "$@"
+  parse_commands "$@"
   cucorr_global_init
   cucorr_toolchain_init
   cucorr_compile
